### PR TITLE
Copy to clipboard

### PR DESCRIPTION
**Pull request by Teddytrombone**
Add possibility to copy currently shown timestamp (left mouse button) or current timestamp (any other mouse button) to clipboard

### CODE REVIEW

**Comment by se1exin** [comment]
Thanks for the PR @Teddytrombone ! It looks good from a glance, I'll give it a proper test soon when I have time to merge and upload to Gnome Extensions.

**Comment by se1exin** [comment]
@Teddytrombone this works well thanks.

Quick question - what is the difference (and rationale) between the currently shown timestamp and the current timestamp? In my testing the copied value will always be the same.

**Comment by Teddytrombone** [comment]
The visible unix timestamp is only updated, when the GnomeDesktop.WallClock gets updated. If you disable the output of seconds then the timestamp is only updated when the minutes part changes  (open gnome-tweaks, go to "Top Bar" and in "Clock" disable or enable  "Seconds" to see the difference).
So you have the same visible timestamp for 60 seconds. I thought that a left click should copy the visible timestamp and any other mouse button copies the "real" timestamp.

**Comment by se1exin** [comment]
I had no idea that was happening! I always have seconds turned on so obviously missed it in testing. Thanks!

If there was a way to have the timestamp always update every second, even if you had seconds disabled, would you want it? Or do you think the timestamp update should stay as-is with the main clock?

**Comment by Teddytrombone** [comment]
To be honest: I don't know. I have seconds disabled, because I find it distracting during work, as there is always a visual change on the screen. I guess it would be the same for me if the timestamp changes. But this is only my opinion. Maybe a configuration setting would be OK, but I guess this makes the extension much more complex ;-)

**Comment by se1exin** [comment]
Interesting, yeh I agree a config setting would be the correct way. I don't have time at the moment to add it, but I'd welcome a PR if you wanted to!

I've submitted and update to Gnome Extensions, and added you as a contributor to the readme. Thanks heaps!

**Pull request merged**
